soc: qcom: event_timer: Fix compilation breakage
Upstream commit 0135fcb ('lib/timerqueue: Rely on rbtree semantics for next timer') changed the timerque struct.

drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
drivers/soc/qcom/event_timer.c:55:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'stru0t timerqueue_head')
        .next = NULL,
         ^
2 errors generated.